/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_1 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] alu,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  wire [16-1:0] M_adder_s;
  reg [16-1:0] M_adder_a;
  reg [16-1:0] M_adder_b;
  reg [4-1:0] M_adder_alufn;
  fasixteen_6 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n),
    .s(M_adder_s)
  );
  
  wire [16-1:0] M_compare_compare;
  reg [1-1:0] M_compare_z;
  reg [1-1:0] M_compare_v;
  reg [1-1:0] M_compare_n;
  reg [2-1:0] M_compare_alufn;
  comparesixteen_7 compare (
    .z(M_compare_z),
    .v(M_compare_v),
    .n(M_compare_n),
    .alufn(M_compare_alufn),
    .compare(M_compare_compare)
  );
  
  wire [16-1:0] M_shifter_shift;
  reg [16-1:0] M_shifter_a;
  reg [4-1:0] M_shifter_b;
  reg [2-1:0] M_shifter_alufn;
  shiftersixteen_8 shifter (
    .a(M_shifter_a),
    .b(M_shifter_b),
    .alufn(M_shifter_alufn),
    .shift(M_shifter_shift)
  );
  
  wire [16-1:0] M_boole_boole;
  reg [4-1:0] M_boole_alufn;
  reg [16-1:0] M_boole_a;
  reg [16-1:0] M_boole_b;
  boolesixteen_9 boole (
    .alufn(M_boole_alufn),
    .a(M_boole_a),
    .b(M_boole_b),
    .boole(M_boole_boole)
  );
  
  always @* begin
    M_adder_a = a;
    M_adder_b = b;
    M_adder_alufn = alufn[0+3-:4];
    M_compare_z = M_adder_z;
    M_compare_v = M_adder_v;
    M_compare_n = M_adder_n;
    M_compare_alufn = alufn[1+1-:2];
    M_shifter_a = a;
    M_shifter_b = b[0+3-:4];
    M_shifter_alufn = alufn[0+1-:2];
    M_boole_a = a;
    M_boole_b = b;
    M_boole_alufn = alufn[0+3-:4];
    
    case (alufn[4+1-:2])
      2'h0: begin
        alu = M_adder_s;
      end
      2'h1: begin
        alu = M_boole_boole;
      end
      2'h2: begin
        alu = M_shifter_shift;
      end
      2'h3: begin
        alu = M_compare_compare;
      end
      default: begin
        alu = 16'h0000;
      end
    endcase
    z = M_adder_z;
    v = M_adder_v;
    n = M_adder_n;
  end
endmodule
